const food = (req, res) => {
    res.send([
        {
            "id": 1,
            "title": "The Vadapav Is Life Of Mumbaikars",
            "Image": "https://i.ndtvimg.com/i/2016-08/oav_625x350_71471093186.jpg",
            "category": "food",
            "description": "When we wake up, the first thing that comes to put mind is what to have for breakfast. After finishing it, we start thinking about lunch and then about dinner. This shows that food is one of the most important parts of our lives. One day we skip a meal, and our body starts reacting in a different way. While what we eat matters, another thing that plays a part is when we eat our meals. The time of having breakfast, lunch and dinner are vital to determine many health benefits. There is a common saying, “Early to bed, early to rise, makes us healthy, wealthy and wise.” Let’s turn it up a little and say, early dinner and early breakfast are all you need to be healthy and smart.Breakfast: Breakfast is the first meal of the day which makes our guts wake up. Usually, breakfast is eaten after 8 to 10 hours of having our dinner. The best time to have the first meal of the day is between 7 am to 9 am.Lunch: When you eat your breakfast early, it gives your stomach enough time to rest before you go on to your lunch. This aids digestion of breakfast. The best time to have lunch is between 12 noon to 2 pm. Dinner: As you have had your lunch early, you might feel hungry soon in the evening. Many dieticians recommend having early dinner in order to satisfy our hunger as well as boost metabolism. You should have your dinner between 6.30 pm to 8 pm.  If you have all your meals on a scheduled time daily, then it can help you boost your metabolism. In the morning, your metabolic rate works best, and as the day passes, it slows down. Therefore, having an early breakfast gives it a boost and an early dinner help it sustain."
          },
            {
              "id": 2,
              "title": "In latest edition of bizarre food experiment, Egg Maggi",
              "Image": "https://th.bing.com/th/id/OIP.WFi0KDgSNqgaOY89YeOEbwHaGU?w=211&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7",
              "category": "Food",
              "description": "Eating the same food regularly may make people lose interest. Hence, often people come up with creative takes to spice it up. However, in order to reinvent people’s favourite Maggi, a street vendor decided to come up with a fruity fix — by adding eggs!Yes, while adding vegetables and other add-ons like egg, chicken or cheese are favoured combinations when it comes to the instant noodles, it has often seen experiments with something sweet before. From unusual cotton candy Maggi to obnoxious Maggi laddu and kheer, desi people on the internet have seen it all. However, it’s the first time fruit was seen being added to it.In a video shared on Instagram by The Great Indian Foodie, a woman is seen making Maggi on a big tawa (skillet), frying the masala in ghee and adding some water before putting the instant noodles in. However, taking inspiration from the previously viral Fanta Maggi, she is seen adding Mango juice to the pan. But what happens next really left all terrified online"
            },
            {
              "id": 3,
              "title": "International Burger Day: 5 Non-Vegetarian Burger Recipes You Must Try",
              "Image": "https://c.ndtvimg.com/2022-04/k9toe6b8_burger_625x300_23_April_22.jpg?im=FeatureCrop,algorithm=dnn,width=620,height=350",
              "category": "Food",
              "description": "Can we call burgers the ultimate comfort food? May be yes! It is because we are running out of options to describe the lip-smackingly delicious snack. Loaded with cheese and mayonnaise, the oh-so-soft buns and the crispy patty have the power to lift our mood at any given day. After all, it is the hearty burgers we are talking about. Be it for breakfast or lunch or dinner, we are always ready for a wholesome burger. And, things get all the better if you have some juicy non-vegetarian burger options to pick from. Relatable, did we hear?! Well, in that case, we have some amazing recipes waiting for you.For the ones who love to relish the taste of lamb with chilli sauce, this recipe is your stop. The soft lamb patty between the buns with the punch of lettuce, and bell peppers, can make you want to have it again and again.The taste of your favourite main course dish combined with a crispy patty screams taste. The soft burger buns with heavenly chicken roasted in the makhana gravy can your tastebuds on a joy ride. Isn't it sound amazing?"
            },
            {
              "id": 4,
              "title": "This viral recipe for ice pizza has left netizens puzzled",
              "Image": "https://th.bing.com/th/id/R.2a85bc9a73a5e0c06aafc58c3aa269cb?rik=QJ21bOKopN5%2fCA&riu=http%3a%2f%2f1.bp.blogspot.com%2f-X0gXXnxzZ3I%2fU7HR3ZT9gOI%2fAAAAAAAACW4%2f4zg5gfxGmVQ%2fs1600%2fDummy%2b15_W.jpg&ehk=0fBbHCAgCln0Q6FSLO9E6%2bK%2b0JcprGDxtrFRsvG9Yf4%3d&risl=&pid=ImgRaw&r=0",
              "category": "Food",
              "description": "If you are on social media, you would have definitely come across some bizarre food videos that left you scratching your head. The latest addition to such food experiments is the ‘ice pizza’. Yes, you read that right!Shared by an Instagram page — ‘Does He Bake Dough’ — the ice pizza recipe has gone viral on the internet, amassing over 1 lakh views and thousands of comments The video shows the chef kneading a soft dough and spreading it with his hands. His next step is what has left netizens puzzled — he topped the dough with three ice cubes before finally placing it into the oven. Next, the chef takes out the freshly baked pizza from the oven and drizzles grated cheese and some condiments over it."
            },
            {
              "id": 5,
              "title": "From vada pav to falooda: Popular street foods you must try in Mumbai",
              "Image": "https://th.bing.com/th/id/OIP.MR1HbP_DlQWgmbJXZRgonQHaE8?w=271&h=180&c=7&r=0&o=5&dpr=1.25&pid=1.7",
              "category": "Food",
              "description": "From Varanasi's baati chokha ko Delhi's golgappas, every city has distinct culinary offerings which reflect the food culture of the place. Here, we bring to you some amazing street food options which are a must-have when you are in Mumbai next. Mumbai's street food begins with vada pav, vegetarian dish which consists of potato patties placed inside a pav (soft bun). But this street delicacy is incomplete without the peanut, garlic and red chilli spread it is served with. Your trip to Mumbai will be incomplete without a hot crispy vada pav.Every city has it's own version of pani puri or golgappa, and Mumbai has it too. The hollow, puffed, round dough ball is filled with a spicy potato-based mixture and dipped in masala water. The ones served in the city are much sweeter."
            },
            {
              "id": 6,
              "title": "When to Have Breakfast, Lunch and Dinner to Get Maximum Benefits?",
              "Image": "https://s-media-cache-ak0.pinimg.com/originals/2c/15/0d/2c150dfb2d8ddfa8ea564a8793ae7417.jpg",
              "category": "Food",
              "description": "When we wake up, the first thing that comes to put mind is what to have for breakfast. After finishing it, we start thinking about lunch and then about dinner. This shows that food is one of the most important parts of our lives. One day we skip a meal, and our body starts reacting in a different way. While what we eat matters, another thing that plays a part is when we eat our meals. The time of having breakfast, lunch and dinner are vital to determine many health benefits. There is a common saying, “Early to bed, early to rise, makes us healthy, wealthy and wise.” Let’s turn it up a little and say, early dinner and early breakfast are all you need to be healthy and smart.Breakfast: Breakfast is the first meal of the day which makes our guts wake up. Usually, breakfast is eaten after 8 to 10 hours of having our dinner. The best time to have the first meal of the day is between 7 am to 9 am.Lunch: When you eat your breakfast early, it gives your stomach enough time to rest before you go on to your lunch. This aids digestion of breakfast. The best time to have lunch is between 12 noon to 2 pm. Dinner: As you have had your lunch early, you might feel hungry soon in the evening. Many dieticians recommend having early dinner in order to satisfy our hunger as well as boost metabolism. You should have your dinner between 6.30 pm to 8 pm.  If you have all your meals on a scheduled time daily, then it can help you boost your metabolism. In the morning, your metabolic rate works best, and as the day passes, it slows down. Therefore, having an early breakfast gives it a boost and an early dinner help it sustain."
            },
            {
              "id": 7,
              "title": "What The Fork: Kunal Vijayakar on the Perfect Summer Food to Beat the Heat",
              "Image": "https://th.bing.com/th/id/OIP._Q2yFQiO077kXe40Je8qKQHaE8?w=297&h=198&c=7&r=0&o=5&dpr=1.25&pid=1.7",
              "category": "Food",
              "description": "​​ How soon we renounce age-old traditions in the praxis of food, and succumb to the allure of convenience, short cuts, and finished good-looking products. I’m talking about age old dahi or curd. In my grandmother’s home where I lived for the first 15 years of my life and even when we moved lock stock and tapeli to where my parents made their new home, dahi was always made in the kitchen. It was a daily process. Every day milk would be boiled and cooled to room temperature. A medium-heavy bottomed pot would be greased with the previous day’s dahi, which worked like a bacterial curd starter, and the boiled warm milk would be poured in. A wet cloth kept the milk covered as nature created magic, fermented the milk, added wonderfully healthy probiotic characteristics, thickened it and set it to curd. It would take four to five hours on a normal warm, hot and humid Mumbai day, eight to 12 in cold weather, that was it. Sometimes we’d make curd two times a day, just to be able to have it fresh. There was also a kind of romantic uncertainty about how well the curd would set. Sometimes it could set loosely, separating the water from the milk and sometimes it would be firm and silky. After all milk wasn’t bought homogenised, standardised and in a carton, but was bought at the doorstep from a doodhwala, whose honesty was always in question. So obviously, the better the milk the better the curd. The pot of milk with the curd starter would always be kept in a warm place and most importantly left alone. One old ladies’ tale was that you could add a green chilly with its stem intact to help the curd set faster. Ostensibly, the chilly with the stem would not impart any taste but contained certain bacteria that activated the milk to produce protein curdles that turned milk into curd faster. I’d actually never seen that happening in any of our kitchens."
            } 
    ])
}

module.exports.apicontrol7 = food;